package com.example.supabase

import com.example.BuildConfig
import com.example.model.CommuteFingerprint
import com.example.model.CrowdLevel
import com.example.model.DelayRisk
import com.example.model.JourneyFeedback
import com.example.model.RouteCategory
import com.example.model.RouteOption
import com.example.model.RouteSegment
import com.example.model.SavedRoute
import com.example.model.ScoreBreakdown
import com.example.model.ToleranceLevel
import com.example.model.TransportType
import com.example.model.UserProfile
import com.example.model.UserRole
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID
import java.util.concurrent.TimeUnit

data class SupabaseSession(
    val accessToken: String?,
    val refreshToken: String?,
    val user: UserProfile?
)

object SupabaseClient {
    private val client = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(15, TimeUnit.SECONDS)
        .writeTimeout(15, TimeUnit.SECONDS)
        .build()

    // Read securely from BuildConfig generated by .env / Secrets panel
    val supabaseUrl: String
        get() = try { BuildConfig.SUPABASE_URL } catch (_: Exception) { "" }

    val supabaseAnonKey: String
        get() = try { BuildConfig.SUPABASE_ANON_KEY } catch (_: Exception) { "" }

    var currentSession: SupabaseSession? = null
        private set

    val isConnectedToLiveSupabase: Boolean
        get() = supabaseUrl.isNotBlank() &&
                !supabaseUrl.contains("your-project") &&
                supabaseAnonKey.isNotBlank() &&
                !supabaseAnonKey.contains("your-supabase-anon-key")

    /**
     * Sign Up via Supabase Auth: POST /auth/v1/signup
     */
    suspend fun signUp(email: String, pass: String, fullName: String): Result<UserProfile> = withContext(Dispatchers.IO) {
        if (!isConnectedToLiveSupabase) {
            // Local verified session
            val role = if (email.contains("admin", ignoreCase = true)) UserRole.ADMIN else UserRole.COMMUTER
            val mockUser = UserProfile(
                id = UUID.randomUUID().toString(),
                name = fullName.ifBlank { email.substringBefore("@") },
                email = email,
                role = role
            )
            currentSession = SupabaseSession("demo_jwt_token", "demo_refresh_token", mockUser)
            return@withContext Result.success(mockUser)
        }

        try {
            val bodyJson = JSONObject().apply {
                put("email", email)
                put("password", pass)
                put("data", JSONObject().apply { put("full_name", fullName) })
            }

            val request = Request.Builder()
                .url("${supabaseUrl.trimEnd('/')}/auth/v1/signup")
                .header("apikey", supabaseAnonKey)
                .header("Content-Type", "application/json")
                .post(bodyJson.toString().toRequestBody("application/json".toMediaType()))
                .build()

            val response = client.newCall(request).execute()
            val resBody = response.body?.string().orEmpty()

            if (response.isSuccessful) {
                val json = JSONObject(resBody)
                val userObj = json.optJSONObject("user") ?: json
                val userId = userObj.optString("id", UUID.randomUUID().toString())
                val token = json.optString("access_token").takeIf { it.isNotEmpty() }
                val role = if (email.contains("admin", ignoreCase = true)) UserRole.ADMIN else UserRole.COMMUTER
                val profile = UserProfile(
                    id = userId,
                    name = fullName.ifBlank { email.substringBefore("@") },
                    email = email,
                    role = role
                )
                val refreshToken = json.optString("refresh_token").takeIf { it.isNotEmpty() }
                currentSession = SupabaseSession(token, refreshToken, profile)
                Result.success(profile)
            } else {
                val err = try { JSONObject(resBody).optString("msg", "Sign up failed") } catch (_: Exception) { "Sign up failed" }
                Result.failure(Exception(err))
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    /**
     * Sign In via Supabase Auth: POST /auth/v1/token?grant_type=password
     */
    suspend fun signIn(email: String, pass: String): Result<UserProfile> = withContext(Dispatchers.IO) {
        if (!isConnectedToLiveSupabase) {
            val role = if (email.contains("admin", ignoreCase = true)) UserRole.ADMIN else UserRole.COMMUTER
            val mockUser = UserProfile(
                id = if (role == UserRole.ADMIN) "admin_super_001" else "usr_naman_101",
                name = if (role == UserRole.ADMIN) "Transit Authority Admin" else "Naman Sharma",
                email = email,
                role = role
            )
            currentSession = SupabaseSession("demo_jwt_token", "demo_refresh_token", mockUser)
            return@withContext Result.success(mockUser)
        }

        try {
            val bodyJson = JSONObject().apply {
                put("email", email)
                put("password", pass)
            }

            val request = Request.Builder()
                .url("${supabaseUrl.trimEnd('/')}/auth/v1/token?grant_type=password")
                .header("apikey", supabaseAnonKey)
                .header("Content-Type", "application/json")
                .post(bodyJson.toString().toRequestBody("application/json".toMediaType()))
                .build()

            val response = client.newCall(request).execute()
            val resBody = response.body?.string().orEmpty()

            if (response.isSuccessful) {
                val json = JSONObject(resBody)
                val token = json.getString("access_token")
                val userObj = json.getJSONObject("user")
                val userId = userObj.getString("id")
                val role = if (email.contains("admin", ignoreCase = true)) UserRole.ADMIN else UserRole.COMMUTER
                val profile = UserProfile(
                    id = userId,
                    name = email.substringBefore("@"),
                    email = email,
                    role = role
                )
                val refreshToken = json.optString("refresh_token").takeIf { it.isNotEmpty() }
                currentSession = SupabaseSession(token, refreshToken, profile)
                Result.success(profile)
            } else {
                val err = try { JSONObject(resBody).optString("error_description", "Invalid login credentials") } catch (_: Exception) { "Invalid login credentials" }
                Result.failure(Exception(err))
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    /**
     * Password recovery via Supabase: POST /auth/v1/recover
     */
    suspend fun resetPassword(email: String): Result<Unit> = withContext(Dispatchers.IO) {
        if (!isConnectedToLiveSupabase) {
            return@withContext Result.success(Unit)
        }

        try {
            val bodyJson = JSONObject().apply { put("email", email) }
            val request = Request.Builder()
                .url("${supabaseUrl.trimEnd('/')}/auth/v1/recover")
                .header("apikey", supabaseAnonKey)
                .header("Content-Type", "application/json")
                .post(bodyJson.toString().toRequestBody("application/json".toMediaType()))
                .build()

            val response = client.newCall(request).execute()
            if (response.isSuccessful) Result.success(Unit) else Result.failure(Exception("Recovery request failed"))
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    /**
     * Sign out / session cleanup
     */
    suspend fun signOut() = withContext(Dispatchers.IO) {
        val token = currentSession?.accessToken
        currentSession = null
        if (isConnectedToLiveSupabase && !token.isNullOrBlank()) {
            try {
                val request = Request.Builder()
                    .url("${supabaseUrl.trimEnd('/')}/auth/v1/logout")
                    .header("apikey", supabaseAnonKey)
                    .header("Authorization", "Bearer $token")
                    .post("{}".toRequestBody("application/json".toMediaType()))
                    .build()
                client.newCall(request).execute()
            } catch (_: Exception) {}
        }
    }

    /**
     * Admin Audit Log Insertion: POST /rest/v1/admin_audit_logs
     */
    suspend fun logAdminAction(adminId: String, action: String, targetId: String, details: String) = withContext(Dispatchers.IO) {
        if (!isConnectedToLiveSupabase) return@withContext

        try {
            val token = currentSession?.accessToken ?: supabaseAnonKey
            val body = JSONObject().apply {
                put("admin_id", adminId)
                put("action", action)
                put("target_id", targetId)
                put("details", JSONObject().apply { put("info", details) })
            }

            val request = Request.Builder()
                .url("${supabaseUrl.trimEnd('/')}/rest/v1/admin_audit_logs")
                .header("apikey", supabaseAnonKey)
                .header("Authorization", "Bearer $token")
                .header("Content-Type", "application/json")
                .post(body.toString().toRequestBody("application/json".toMediaType()))
                .build()

            client.newCall(request).execute()
        } catch (_: Exception) {}
    }
}
